--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.107.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 17-12-2019 06:39:15 PM
-- Server version: 14.00.1000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT easy_travels.dbo.enquiry(enquiry_id, employee_id, customer_id, enquiry_detail, enquiry_type, created_on, required_days, required_nights, required_country) VALUES (N'02507b42-a023-4271-929d-4d5abecb620b', '6848be80-5c58-4d4f-b11f-d1e76f6c92b5', 'a81230ab-1510-46e2-b9b4-64fd62fc9911', 'Urgent requirement for Portugal', 'INTERNATIONAL', '2019-12-17 15:35:59.220', 5, 4, 'Portugal')
INSERT easy_travels.dbo.enquiry(enquiry_id, employee_id, customer_id, enquiry_detail, enquiry_type, created_on, required_days, required_nights, required_country) VALUES (N'4cd27bba-88d8-4d2c-8ee1-86d2ca66e615', '6848be80-5c58-4d4f-b11f-d1e76f6c92b5', '45b83100-e7aa-448e-8447-d023c949e799', 'Looking for 5 dayl holiday package in North Indian', 'DOMESTIC', '2019-12-13 23:30:58.613', 5, 4, 'India')
INSERT easy_travels.dbo.enquiry(enquiry_id, employee_id, customer_id, enquiry_detail, enquiry_type, created_on, required_days, required_nights, required_country) VALUES (N'6da738d0-c680-4df9-8080-769d2e889f44', '6848be80-5c58-4d4f-b11f-d1e76f6c92b5', 'ee3c1ac0-9c7f-4353-bd78-a72c3d2225b1', 'Kanaykumari 9 days', 'DOMESTIC', '2019-12-17 15:37:19.970', 9, 8, 'India')
INSERT easy_travels.dbo.enquiry(enquiry_id, employee_id, customer_id, enquiry_detail, enquiry_type, created_on, required_days, required_nights, required_country) VALUES (N'b31cd01b-f3d0-4156-b5b7-2896023b8765', '6848be80-5c58-4d4f-b11f-d1e76f6c92b5', 'a81230ab-1510-46e2-b9b4-64fd62fc9911', 'Want to visit to Singapore in this winter', 'INTERNATIONAL', '2019-12-13 23:19:39.753', 5, 4, 'Singapore')
INSERT easy_travels.dbo.enquiry(enquiry_id, employee_id, customer_id, enquiry_detail, enquiry_type, created_on, required_days, required_nights, required_country) VALUES (N'c90011b2-2082-4cf6-9dc5-62ad6bbd54d3', '6848be80-5c58-4d4f-b11f-d1e76f6c92b5', '4bbfe99e-c7fa-46c5-bd84-62bd1b488611', 'Have to visit to london for office work', 'INTERNATIONAL', '2019-12-13 23:28:46.010', 3, 2, 'England')
GO