--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.107.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 17-12-2019 06:39:15 PM
-- Server version: 14.00.1000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT easy_travels.dbo.employee_role_mapping(mapping_id, employee_id, role_id, created_on) VALUES (N'4af729be-7089-43f6-bc19-9fca6d3726ee', '6848be80-5c58-4d4f-b11f-d1e76f6c92b5', 4, '2019-12-13 23:17:47.983')
INSERT easy_travels.dbo.employee_role_mapping(mapping_id, employee_id, role_id, created_on) VALUES (N'a3c5f7a9-5c63-4788-a4b9-5d2652354031', '02b10ba6-4853-4442-b5a3-5697367fd122', 1, '2019-12-17 14:12:28.193')
INSERT easy_travels.dbo.employee_role_mapping(mapping_id, employee_id, role_id, created_on) VALUES (N'a8b0ac6a-8c0b-4480-a9c3-ef86479df89f', '9eb496f7-449a-4db4-8cf4-1f9c02ddec3f', 3, '2019-12-17 14:12:54.490')
INSERT easy_travels.dbo.employee_role_mapping(mapping_id, employee_id, role_id, created_on) VALUES (N'ad521239-9107-43ef-8c9e-c6f6d6c5118e', 'a3444f02-3272-44bb-8507-4f96d6573f8f', 5, '2019-12-17 15:13:48.427')
INSERT easy_travels.dbo.employee_role_mapping(mapping_id, employee_id, role_id, created_on) VALUES (N'ff3a7226-49a3-42ff-a842-1a7be63fc1b0', 'f8bc75b0-7b89-4a56-942e-139426b77483', 2, '2019-12-09 20:56:24.517')
GO