--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.107.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 17-12-2019 06:39:15 PM
-- Server version: 14.00.1000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT easy_travels.dbo.employee(employee_id, name, username, password, email, contact_no, session_id, created_on) VALUES (N'02b10ba6-4853-4442-b5a3-5697367fd122', 'Pratik Yadav', 'psy_1234', 'ydava@pratik', 'ypyadav@gmail.com', '9898956556', NULL, '2019-12-17 14:10:53.440')
INSERT easy_travels.dbo.employee(employee_id, name, username, password, email, contact_no, session_id, created_on) VALUES (N'6848be80-5c58-4d4f-b11f-d1e76f6c92b5', 'Manik Mahashabde', 'manik_123', 'man@1991', 'manik@mydbs.ie', '867866545', NULL, '2019-12-09 20:51:27.437')
INSERT easy_travels.dbo.employee(employee_id, name, username, password, email, contact_no, session_id, created_on) VALUES (N'9eb496f7-449a-4db4-8cf4-1f9c02ddec3f', 'Sagar Patil', 'patil_sagar', 'sg@1995', 'sagar.patil@gmail.com', '5645345454', NULL, '2019-12-17 14:09:04.393')
INSERT easy_travels.dbo.employee(employee_id, name, username, password, email, contact_no, session_id, created_on) VALUES (N'a3444f02-3272-44bb-8507-4f96d6573f8f', 'Sabitha Maram', 'sabitha@1997', 'sab_maram', 'sabitha@gmail.com', '9565968595', NULL, '2019-12-09 20:52:27.907')
INSERT easy_travels.dbo.employee(employee_id, name, username, password, email, contact_no, session_id, created_on) VALUES (N'f8bc75b0-7b89-4a56-942e-139426b77483', 'Saurabh Devade', 'saurabh_123', 'pass@123', 'saurabh.devade21@gmail.com', '897646767', 'f8bc75b0-7b89-4a56-942e-139426b774831576433659993', '2019-12-09 20:44:02.313')
GO