--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.107.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 17-12-2019 06:39:15 PM
-- Server version: 14.00.1000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT easy_travels.dbo.booking(booking_id, customer_id, package_id, created_on) VALUES (N'4c724dbc-98f3-4356-8851-949706719eba', 'a81230ab-1510-46e2-b9b4-64fd62fc9911', '10ddc398-4405-48ad-ab5f-95322451eff3', '2019-12-13 22:05:43.780')
INSERT easy_travels.dbo.booking(booking_id, customer_id, package_id, created_on) VALUES (N'7b0c4caf-e020-43d7-99fa-7fb1aac9cfe5', '4bbfe99e-c7fa-46c5-bd84-62bd1b488611', '50fe2bda-706c-40e9-902a-63a3b76d6b0e', '2019-12-27 15:09:05.887')
INSERT easy_travels.dbo.booking(booking_id, customer_id, package_id, created_on) VALUES (N'7bc3ba6d-b35f-4f97-a6a4-acf4a3fd3ead', 'ee3c1ac0-9c7f-4353-bd78-a72c3d2225b1', 'b7c12385-856d-46b4-bd05-954a531c7444', '2019-12-17 15:11:59.703')
INSERT easy_travels.dbo.booking(booking_id, customer_id, package_id, created_on) VALUES (N'a6f9974d-55d6-4971-b7d8-873f51471400', '4bbfe99e-c7fa-46c5-bd84-62bd1b488611', 'a13ad548-639c-4462-83d0-d858b23b341c', '2019-12-17 15:10:27.107')
INSERT easy_travels.dbo.booking(booking_id, customer_id, package_id, created_on) VALUES (N'ccf59898-ea33-47b6-a619-492741778ba2', 'a81230ab-1510-46e2-b9b4-64fd62fc9911', 'bc6637bf-21f6-4bac-84b3-fa016321b89b', '2019-12-17 15:12:29.050')
INSERT easy_travels.dbo.booking(booking_id, customer_id, package_id, created_on) VALUES (N'cfaa8810-cd66-4450-bed4-9b4414490e5f', '45b83100-e7aa-448e-8447-d023c949e799', '10ddc398-4405-48ad-ab5f-95322451eff3', '2019-12-17 14:16:21.587')
GO