--
-- Script was generated by Devart dbForge Studio 2019 for SQL Server, Version 5.8.107.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 17-12-2019 06:39:15 PM
-- Server version: 14.00.1000
--

SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO

INSERT easy_travels.dbo.customer(customer_id, name, username, password, email, contact_no, session_id, created_on) VALUES (N'45b83100-e7aa-448e-8447-d023c949e799', 'Aatmaj Deshmukh', 'atdeshmukh89', '89deshaat', 'aatmaj@intel.co.in', '65655656454', NULL, '2019-12-13 23:23:57.503')
INSERT easy_travels.dbo.customer(customer_id, name, username, password, email, contact_no, session_id, created_on) VALUES (N'4bbfe99e-c7fa-46c5-bd84-62bd1b488611', 'Kaustubh Kadam', 'kustubh@amazon.co', 'k#k23', 'kadam_me', '5416545454', NULL, '2019-12-13 23:22:39.280')
INSERT easy_travels.dbo.customer(customer_id, name, username, password, email, contact_no, session_id, created_on) VALUES (N'a81230ab-1510-46e2-b9b4-64fd62fc9911', 'Vineet Sawant', 'vinit_123', 'pass@123', 'vinit@gmail.com', '8956846854', NULL, '2019-12-13 22:04:42.423')
INSERT easy_travels.dbo.customer(customer_id, name, username, password, email, contact_no, session_id, created_on) VALUES (N'ee3c1ac0-9c7f-4353-bd78-a72c3d2225b1', 'Avdhoot Hande', 'avd@1234', '23123212', 'avd@hnade.com', '51231231531', NULL, '2019-12-17 15:11:27.510')
GO